### ISSUE TITLE
探针最后一栏【联通 | 电信 | 移动】显示不全

### ISSUE THREAD

**Issue by honorcnboy** [zdz/ServerStatus-Rust#107]
大佬，脚本部署，1.57版本，尝试了3款浏览器：360，Chrome，Firefox，在最后一栏的【联通 | 电信 | 移动】显示不全。

请教下，应该怎么解决？

恐表述不清，直接上图说明（标记红框处就是显示有缺的）

Chrome【100%显示比例，最后一列标题还出现了换行，对应数据显示不全】：
![image](https://user-images.githubusercontent.com/68975045/203821388-5a39129b-87d2-4e8a-a358-08020f1a8042.png)

Firefox【100%显示比例，最后一列标题单行正常，对应数据显示不全】：
![image](https://user-images.githubusercontent.com/68975045/203821435-b2c0d3b2-2ba3-4fc0-81ad-d052c0f404cb.png)

360【100%显示比例，最后一列标题单行正常，对应数据显示不全】：
![image](https://user-images.githubusercontent.com/68975045/203821482-b30dcc55-c893-4e57-a2c4-bd1286440ada.png)

**Comment by Glory-CNBoy** [comment]
学习到了，感谢佬

**Comment by Glory-CNBoy** [comment]
> 可以试试 [v1.6.0](https://github.com/zdz/ServerStatus-Rust/releases/tag/v1.6.0) 版

已经使用1.6.0，简单说说个人感受。当然，萝卜白菜各有所爱，所以仅代表个人感受：
1. 增加的labels功能真的很实用，很不错！
2. 就个人而言，更喜欢1.5.7的web展示效果，看起来没有那么花。可能年龄不小了，偏爱沉稳一点的。哈哈哈！
3. 地图 跟 参数 两个页面的快捷进入图标没了，只能手动更改链接进入，可能主题还在修改中，后期应该会加上吧。
4. 还有一个小问题，升级版本，我采用的是，备份配置文件，重新快捷安装，然后再把备份的配置文件中的服务器配置等修改过的参数粘贴进新文件。有无更方便的办法？

总体而言，好的作品，感谢大佬的项目，以及坚持不停的轮子。
