### ISSUE TITLE
自定义ping服务器

### ISSUE THREAD

**Issue by VV-1024** [zdz/ServerStatus-Rust#11]
请问一下ping服务器可以成修改指定服务器吗

**Comment by zdz** [comment]
可以，修改这里即可 @VV-1024 
https://github.com/zdz/ServerStatus-Rust/blob/a16aca32719a465323d4274e5f4f94f5a4c35c61/client/src/status.rs#L27

**Comment by VV-1024** [comment]
啊这，我不会重新编译，还有更简单一点的方法吗，我看见你这个都是打包好的，或者能直接修改吗

**Comment by zdz** [comment]
不能直接修改，或者你可以改python版，不用重新编译
https://github.com/zdz/ServerStatus-Rust/blob/a16aca32719a465323d4274e5f4f94f5a4c35c61/client/client-linux.py#L18

**Comment by zdz** [comment]
@VV-1024 重新编译的步骤 
```
curl -sSf https://static.rust-lang.org/rustup.sh | sh
https://github.com/zdz/ServerStatus-Rust.git
cd ServerStatus-Rust
yum install -y openssl-devel
cargo build --release
编译好的文件目录 target/release
```

**Comment by VV-1024** [comment]
感谢大佬，我试一下

**Comment by VV-1024** [comment]
为什么我编译出来的变得好大，好像也启动不了，文件足足有7MB

**Comment by zdz** [comment]
> 为什么我编译出来的变得好大，好像也启动不了，文件足足有7MB
@VV-1024  这是因为github action编译打包时用upx处理过的，你也可以在你的github库里打个tag，如v1.3.2，来触发用 github action 来编译打包

https://github.com/zdz/ServerStatus-Rust/blob/19a1734d1b42d04f1757192339ea50ddd9b7b867/.github/workflows/release.yml#L41
https://github.com/zdz/ServerStatus-Rust/blob/19a1734d1b42d04f1757192339ea50ddd9b7b867/.github/workflows/release.yml#L52

**Comment by VV-1024** [comment]
只是文件上大小有区别的吗?性能什么不影响的话就不管了，但是ping值改了之后似乎也不是很好用
![Uploading SmartSelect_20220330-092043_Via.jpg…]()
![Uploading SmartSelect_20220330-092043_Via.jpg…]()

**Comment by VV-1024** [comment]
![SmartSelect_20220330-092149_Termius](https://user-images.githubusercontent.com/72665660/160732095-81cf7cd8-4898-4087-945b-2d3cf9fc1273.jpg)
![SmartSelect_20220330-092043_Via](https://user-images.githubusercontent.com/72665660/160732110-53f32401-1a67-4b37-81cf-5ecd54994321.jpg)

**Comment by zdz** [comment]
不影响性能，这个如何定义好用？这个只是给你提供你vps到目标地址一种网络延时度量的参考

**Comment by VV-1024** [comment]
懂了，刚刚测了一下路由，azhk联通也绕道日本去了，怪不得ping不对劲

**Comment by VV-1024** [comment]
![SmartSelect_20220402-163655_Nekogram](https://user-images.githubusercontent.com/72665660/161374922-9d3e7f40-947f-4d72-8082-4d99a0b82573.jpg)
离线通知应该怎么改才能显示备注的那个名字呢，显示用户名不太好区分

**Comment by VV-1024** [comment]
看不太懂那个文件😢

**Comment by zdz** [comment]
host.name 改为 host.alias

**Comment by zdz** [comment]
额，模板那个改不了，后面我改个版本支持一下

**Comment by VV-1024** [comment]
好的，我重新再编译一个版本

**Comment by VV-1024** [comment]
大佬，你这个探针真的太好用了，简约不简单👍
![SmartSelect_20220402-174424_Nekogram](https://user-images.githubusercontent.com/72665660/161377525-844795e9-3d41-4581-82e1-6ae90010d49a.jpg)

**Comment by zdz** [comment]
自己定制得不错，欢迎DIY 👍

**Comment by zdz** [comment]
https://github.com/zdz/ServerStatus-Rust/releases/tag/v1.3.2
