### ISSUE TITLE
cpu使用率

### ISSUE THREAD

**Issue by Wangsc1** [zdz/ServerStatus-Rust#12]
大佬能加个cpu使用率吗，感谢🙏

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by zdz** [comment]
处理器那列 那个就是CPU 使用率

**Comment by Wangsc1** [comment]
> 处理器那列就是CPU 使用率

不好意思没说清楚，是cpu使用超过多少就推送，目前不是只有内存和硬盘嘛

**Comment by zdz** [comment]
你可以在模板后面追加以下内容实现
```
{% if host.cpu   > 90  %}
<pre>❗{{ host.name }} 主机CPU使用率超90%, 当前{{ host.cpu }}% </pre>
{% endif %}
```

**Comment by Wangsc1** [comment]
> {% if host.cpu > 90  %}
> <pre>❗{{ host.name }} 主机CPU使用率超90%, 当前{{ host.cpu }}% </pre>
> {% endif %}

好的，感谢
