### ISSUE TITLE
必须重启机器才能更新配置文件吗

### ISSUE THREAD

**Issue by AIEOV** [zdz/ServerStatus-Rust#214]
请教个问题
1  小鸡1安装好服务端   小鸡2安装客户端  （此时未更改配置文件的情况 用默认的账号密码） 网页看不到小鸡2。
   reboot小鸡2  网页能看到了。
2 服务端更改配置文件  刷新网页看不到更改的信息 ， reboot  安装服务端的小鸡1  再刷新能看到了。

所以无论是修改配置文件 还是给新机子装客户端 都需要重启才能生效吗

**Comment by fjiabinc** [comment]
> 请教个问题 1 小鸡1安装好服务端 小鸡2安装客户端 （此时未更改配置文件的情况 用默认的账号密码） 网页看不到小鸡2。 reboot小鸡2 网页能看到了。 2 服务端更改配置文件 刷新网页看不到更改的信息 ， reboot 安装服务端的小鸡1 再刷新能看到了。
> 
> 所以无论是修改配置文件 还是给新机子装客户端 都需要重启才能生效吗

不至于重启机器，重启一下服务就行
