### ISSUE TITLE
monthstart = 1, disabled = false这两个参数做什么用的

### ISSUE THREAD

**Issue by BaeKey** [zdz/ServerStatus-Rust#22]
我翻阅了参考的链接和直接搜索了这两个参数，没有找到相关的说明

并且我使用 railway 部署遇到了favicon.ico无法部署到 railway 的问题，就是直接访问 网站地址/favicon.ico 时候出现了404，我在index.html里面从新指向到了 img/favicon.ico 后，图标才从新加载出来

**Comment by zdz** [comment]
感谢反馈
1. favicon.ico 404 是 bug，下个版本修复，
2. monthstart = 1, 是没启用vnstat时，用来重置月流量统计用的，表示月流量从每月哪天开始统计
3. disabled = true, 是禁用这个主机的配置，相当于这条主机配置不生效，前端不会展示这个主机

**Comment by BaeKey** [comment]
> 感谢反馈
> 
> 1. favicon.ico 404 是 bug，下个版本修复，
> 2. monthstart = 1, 是没启用vnstat时，用来重置月流量统计用的，表示月流量从每月哪天开始统计
> 3. disabled = true, 是禁用这个主机的配置，相当于这条主机配置不生效，前端不会展示这个主机

知道了，谢谢，第一个我还能猜出来可能是和流量有挂，不过已经启用了vnstat，这个就不管了，disabled这个我还真不知道是禁用什么的，非常感谢恢复

**Comment by zdz** [comment]
https://github.com/zdz/ServerStatus-Rust/releases/tag/v1.3.7
