### ISSUE TITLE
中国联通的测试网站down了

### ISSUE THREAD

**Issue by i207M** [zdz/ServerStatus-Rust#248]
RT, 访问`http://cu.tz.cloudapp.com/`提示找不到IP地址。探针的CU延迟也全变成1000ms了。请问`cloudcpp.com`是中国某个机构的域名，还是作者自己的？谢谢

**Comment by yorunning** [comment]
重启客户端，cpp那边的cu地址已恢复

**Comment by i207M** [comment]
恢复了，谢谢！
