### ISSUE TITLE
[Bug] 服务管理脚本的“升级”功能无效

### ISSUE THREAD

**Issue by Nigel-NI** [zdz/ServerStatus-Rust#292]
### Checklist

- [X] 我已经将版本更新到最新 Release 版
- [X] 我已经详细阅读文档, 仍然无法解决
- [X] 我已经搜索已有的 Issues | Discussions, 仍然无法解决
- [X] 我已经尝试过 Google 搜索仍然无法解决

### 💻 系统环境

Debian

### 🐛 问题描述

执行` bash status.sh -up -c`，命令行返回如下内容：
![image](https://github.com/zdz/ServerStatus-Rust/assets/23294384/f5391fc0-e596-4e84-a2fb-b574e4faffb8)
且再次执行该指令，返回的内容如下：
```
[信 息 ] 当 前  Client 版 本 为  v1.8.0
[信 息 ] 当 前  Client 版 本 已 是 最 新 版 本  v1.8.0
```
然而通过`bash status.sh -c status`指令，可以看到正在运行的客户端或服务端仍旧是更新前的版本: 
Feb 19 09:17:22 ooo stat_client[31123]: sys info:  {"name":"oo",**"version":"1.7.2"**,"os_name":ooo ...

手动定位到systemctl服务中的客户端或服务端文件夹，执行`./stat_client -V ` 或 `./stat_server -V`，输出结果如下：
`stat_server v1.7.2 (f2bbe95, 2023-05-28 04:08:36 UTC, rustc 1.69.0, aarch64-unknown-linux-musl)`
`stat_client v1.7.2 (f2bbe95, 2023-05-28 04:07:22 UTC, rustc 1.69.0, x86_64-unknown-linux-musl)`
说明脚本尽管输出了类似“更新成功”的提示，但实际上未能正常更新客户端或服务端。

### 🚦 期望结果

 1，`bash status.sh -up`功能可正常更新脚本，

2，执行`bash status.sh -c/-s status`或`./stat_client -V ` 或 `./stat_server -V`等指令时输出的版本号应为最新版

### 📷 复现步骤

1，版本更新前（如1.7.2版本）利用服务管理脚本安装客户端或服务端（bash status.sh -i -c/-s），

2，版本更新后（如当前最新版1.8.0版本）输入`bash status.sh -up -c`指令两次，

3，待脚本提示“当前Client/Server已是最新版本1.8.0”后，输入`bash status.sh -c/-s status`，检查“sys info:” 行 "version"处对应的版本号。

4，定位到/opt/Serverstatus/client或server，输入`./stat_client -V ` 或 `./stat_server -V`检查当前版本。

**Comment by yorunning** [comment]
同样遇到这个问题，几台ubuntu22能用脚本升级，ubuntu20、debian11不行
