### ISSUE TITLE
[Request] 希望增加历史tcping图表功能

### ISSUE THREAD

**Issue by Nigel-NI** [zdz/ServerStatus-Rust#293]
### 🥰 需求描述

希望推出tcping历史图表功能，便于观察过去一段时间内网络波动情况。

### 🧐 解决方案

类似于已有的地图或详细表功能，在新页面上显示出各主机最近若干小时内的网络延迟曲线图，参考[nezha demo](https://ops.naibahq.com/network)，如图所示：
<img width="1354" alt="image" src="https://github.com/zdz/ServerStatus-Rust/assets/23294384/fd7864bf-2317-4e6b-b2dd-cfb55423ebd4">

### 📝 补充信息

这个功能请求可能工作量较大，倘若本issue能最终落地，不胜感激，谢谢！

**Comment by SkysCrystal** [comment]
请问这个功能如何开启呢？
